version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: crud-kotlin-app
    environment:
      POSTGRES_DB: jdbc:postgresql://localhost:5432/pgDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: your-spring-boot-container-name
    ports:
      - 8080:8080
    depends_on:
      - postgres
